### ISSUE TITLE
Bug: Use text-overflow to allow for better readability

### ISSUE THREAD

**Issue by amilajack** [falcon-client/falcon#26]
Here's an example of case where columns of small widths can cause readability issues (see the last two rows).

<img width="282" alt="screen shot 2017-06-24 at 1 59 51 am" src="https://user-images.githubusercontent.com/6374832/27507302-0f7bfefe-5881-11e7-8182-ea06ebb76a9a.png">

Using the text-overflow css property can solve this.

**Comment by jooohhn** [comment]
Did you want the ability to scroll through it or something like that?

**Comment by jooohhn** [comment]
Nevermind, I understand. Will have `text-overflow: ellipsis` in the next commit
