### ISSUE TITLE
Bug: Rendering too many rows

### ISSUE THREAD

**Issue by amilajack** [falcon-client/falcon#27]
Ideally, if the number of rows is less than the pagination limit, it will only render the minimal amount of rows to fill up the height of the grid.

<img width="821" alt="screen shot 2017-06-24 at 2 02 20 am" src="https://user-images.githubusercontent.com/6374832/27507314-62f4ee74-5881-11e7-9a4c-1baf1f456cfb.png">

Rows 1-15 can fit in the height of the table. But we can scroll past the last row, which doesn't make sense. This is an issue with react-table. We should file a bug there and submit a PR to fix this.

**Comment by jooohhn** [comment]
Fixed with new commit
