### ISSUE TITLE
Enhancement: Button should not take up 100% of row

### ISSUE THREAD

**Issue by amilajack** [falcon-client/falcon#28]
<img width="440" alt="screen shot 2017-06-24 at 2 06 11 am" src="https://user-images.githubusercontent.com/6374832/27507333-c6922c80-5881-11e7-9514-9b99f5878de2.png">

Querious does this well:
<img width="367" alt="screen shot 2017-06-24 at 2 07 07 am" src="https://user-images.githubusercontent.com/6374832/27507336-de270604-5881-11e7-843f-188b28db4eae.png">

**Comment by jooohhn** [comment]
<img width="409" alt="screen shot 2017-06-24 at 4 31 40 pm" src="https://user-images.githubusercontent.com/15751908/27512596-acacea20-58fa-11e7-9f9c-38556aedc958.png">

Better?

**Comment by amilajack** [comment]
Much better!
