### ISSUE TITLE
PR: Initial e2e tests

### ISSUE THREAD

**Issue by amilajack** [falcon-client/falcon#30]
- [x] Assert the values of the rows when clicking on certain tables
- [x] Assert that the title is "Falcon"
- [x] Assert that values change after user edits a cell
- [ ] Run e2e tests on CI

Use [pct e2e tests](https://github.com/amilajack/popcorn-time-desktop/blob/release-0.0.6-alpha/test/e2e.spec.js) as an example

**Comment by jooohhn** [comment]
Not exactly sure how we're going to run the e2e tests if the sqlite file is going to be corrupted
