### ISSUE TITLE
PR: Update flow typings

### ISSUE THREAD

**Issue by jooohhn** [falcon-client/falcon#91]
## Problem
* Project is showing a lot of flow errors
![image](https://user-images.githubusercontent.com/15751908/30769724-dcb0f7b4-9fd3-11e7-8b8e-2388414705a1.png)
* I believe the problem lies in flow@0.53 changing up how `state` and `prop` typings are defined

## Solution
Redefine all typings in accordance to https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

**Comment by amilajack** [comment]
See https://github.com/chentsulin/electron-react-boilerplate/pull/1166/commits/698837e995cb3d03c1fa7beb360156c50d6fb516

**Comment by jooohhn** [comment]
Closed by #92

**Comment by jooohhn** [comment]
Closed by #92
